Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vbguest.auto_update = true

  config.vm.define "ssianS" do |control|
    control.vm.hostname = "ssianS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    control.vm.provision "shell", path: "./scripts/server.sh"
  end

  config.vm.define "ssianSW" do |worker|
    worker.vm.hostname = "ssianSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    worker.vm.provision "shell", path: "./scripts/worker.sh"
  end

end
